{
  'Extract Variable': 144,
  'Change Variable Type': 66,
  'Rename Variable': 74,
  'Change Attribute Type': 28,
  'Remove Attribute Modifier': 18,
  'Extract Superclass': 0,
  'Move Attribute': 19,
  'Change Attribute Access Modifier': 27,
  'Add Attribute Modifier': 27,
  'Pull Up Attribute': 0,
  'Pull Up Method': 0,
  'Remove Thrown Exception Type': 11,
  'Move Method': 47,
  'Change Return Type': 58,
  'Rename Parameter': 166,
  'Change Parameter Type': 130,
  'Localize Parameter': 2,
  'Add Parameter': 238,
  'Rename Method': 56,
  'Rename Attribute': 29,
  'Modify Attribute Annotation': 2,
  'Remove Parameter': 54,
  'Add Method Annotation': 78,
  'Change Method Access Modifier': 65,
  'Inline Method': 210,
  'Extract Method': 824,
  'Remove Class Modifier': 4,
  'Remove Parameter Modifier': 4,
  'Add Variable Modifier': 4,
  'Inline Variable': 17,
  'Remove Method Modifier': 20,
  'Add Class Modifier': 6,
  'Replace Loop With Pipeline': 0,
  'Add Method Modifier': 13,
  'Extract And Move Method': 146,
  'Add Class Annotation': 2,
  'Change Type Declaration Kind': 0,
  'Parameterize Variable': 40,
  'Encapsulate Attribute': 18,
  'Replace Attribute With Variable': 14,
  'Move And Inline Method': 6,
  'Modify Parameter Annotation': 0,
  'Remove Method Annotation': 6,
  'Modify Method Annotation': 2,
  'Remove Variable Modifier': 8,
  'Move Class': 6,
  'Replace Anonymous With Lambda': 8,
  'Change Class Access Modifier': 4,
  'Extract Interface': 2,
  'Add Parameter Modifier': 4,
  'Extract Attribute': 3,
  'Rename Class': 8,
  'Replace Variable With Attribute': 12,
  'Modify Class Annotation': 0,
  'Add Thrown Exception Type': 8,
  'Remove Variable Annotation': 0,
  'Move And Rename Method': 13,
  'Reorder Parameter': 0,
  'Change Thrown Exception Type': 0,
  'Extract Class': 16,
  'Push Down Attribute': 3,
  'Add Attribute Annotation': 16,
  'Remove Attribute Annotation': 1,
  'Replace Pipeline With Loop': 3,
  'Move And Rename Attribute': 1,
  'Remove Class Annotation': 1,
  'Extract Subclass': 5,
  'Push Down Method': 1,
  'Merge Parameter': 10,
  'Merge Variable': 2,
  'Split Parameter': 9,
  'Parameterize Attribute': 4,
  'Move And Rename Class': 0,
  'Merge Class': 2
}

2825