{
  'Extract Variable': 48,
  'Change Variable Type': 68,
  'Rename Variable': 58,
  'Change Attribute Type': 9,
  'Remove Attribute Modifier': 5,
  'Extract Superclass': 0,
  'Move Attribute': 6,
  'Change Attribute Access Modifier': 9,
  'Add Attribute Modifier': 9,
  'Pull Up Attribute': 1,
  'Pull Up Method': 0,
  'Remove Thrown Exception Type': 7,
  'Move Method': 4,
  'Change Return Type': 24,
  'Rename Parameter': 60,
  'Change Parameter Type': 44,
  'Localize Parameter': 0,
  'Add Parameter': 18,
  'Rename Method': 10,
  'Rename Attribute': 9,
  'Modify Attribute Annotation': 0,
  'Remove Parameter': 8,
  'Add Method Annotation': 40,
  'Change Method Access Modifier': 13,
  'Inline Method': 23,
  'Extract Method': 439,
  'Remove Class Modifier': 1,
  'Remove Parameter Modifier': 0,
  'Add Variable Modifier': 0,
  'Inline Variable': 6,
  'Remove Method Modifier': 2,
  'Add Class Modifier': 2,
  'Replace Loop With Pipeline': 0,
  'Add Method Modifier': 1,
  'Extract And Move Method': 110,
  'Add Class Annotation': 0,
  'Change Type Declaration Kind': 0,
  'Parameterize Variable': 4,
  'Encapsulate Attribute': 18,
  'Replace Attribute With Variable': 0,
  'Move And Inline Method': 2,
  'Modify Parameter Annotation': 0,
  'Remove Method Annotation': 6,
  'Modify Method Annotation': 0,
  'Remove Variable Modifier': 4,
  'Move Class': 1,
  'Replace Anonymous With Lambda': 0,
  'Change Class Access Modifier': 1,
  'Extract Interface': 0,
  'Add Parameter Modifier': 0,
  'Extract Attribute': 6,
  'Rename Class': 1,
  'Replace Variable With Attribute': 22,
  'Modify Class Annotation': 0,
  'Add Thrown Exception Type': 4,
  'Remove Variable Annotation': 2,
  'Move And Rename Method': 2,
  'Reorder Parameter': 8,
  'Change Thrown Exception Type': 6,
  'Extract Class': 0,
  'Push Down Attribute': 0,
  'Add Attribute Annotation': 0,
  'Remove Attribute Annotation': 0,
  'Replace Pipeline With Loop': 0,
  'Move And Rename Attribute': 0,
  'Remove Class Annotation': 0,
  'Extract Subclass': 0,
  'Push Down Method': 0,
  'Merge Parameter': 0,
  'Merge Variable': 0,
  'Split Parameter': 0,
  'Parameterize Attribute': 0,
  'Move And Rename Class': 0,
  'Merge Class': 0
}
1121