"Extract Variable",
  "Change Variable Type",
  "Rename Variable",
  "Change Attribute Type",
  "Remove Attribute Modifier",
  "Extract Superclass",
  "Move Attribute",
  "Change Attribute Access Modifier",
  "Add Attribute Modifier",
  "Pull Up Attribute",
  "Pull Up Method",
  "Remove Thrown Exception Type",
  "Move Method",
  "Change Return Type",
  "Rename Parameter",
  "Change Parameter Type",
  "Localize Parameter",
  "Add Parameter",
  "Rename Method",
  "Rename Attribute",
  "Modify Attribute Annotation",
  "Remove Parameter",
  "Add Method Annotation",
  "Change Method Access Modifier",
  "Inline Method",
  "Extract Method",
  "Remove Class Modifier",
  "Remove Parameter Modifier",
  "Add Variable Modifier",
  "Inline Variable",
  "Remove Method Modifier",
  "Add Class Modifier",
  "Replace Loop With Pipeline",
  "Add Method Modifier",
  "Extract And Move Method",
  "Add Class Annotation",
  "Change Type Declaration Kind",
  "Parameterize Variable",
  "Encapsulate Attribute",
  "Replace Attribute With Variable",
  "Move And Inline Method",
  "Modify Parameter Annotation",
  "Remove Method Annotation",
  "Modify Method Annotation",
  "Remove Variable Modifier",
  "Move Class",
  "Replace Anonymous With Lambda",
  "Change Class Access Modifier",
  "Extract Interface",
  "Add Parameter Modifier",
  "Extract Attribute",
  "Rename Class",
  "Replace Variable With Attribute",
  "Modify Class Annotation",
  54;
