rr = [
  "Extract Variable",
  "Change Variable Type",
  "Rename Variable",
  "Change Attribute Type",
  "Remove Attribute Modifier",
  "Extract Superclass",
  "Move Attribute",
  "Change Attribute Access Modifier",
  "Add Attribute Modifier",
  "Pull Up Attribute",
  "Pull Up Method",
  "Remove Thrown Exception Type",
  "Move Method",
  "Change Return Type",
  "Rename Parameter",
  "Change Parameter Type",
  "Localize Parameter",
  "Add Parameter",
  "Rename Method",
  "Rename Attribute",
  "Modify Attribute Annotation",
  "Remove Parameter",
  "Add Method Annotation",
  "Change Method Access Modifier",
  "Inline Method",
  "Extract Method",
  "Remove Class Modifier",
  "Remove Parameter Modifier",
  "Add Variable Modifier",
  "Inline Variable",
  "Remove Method Modifier",
  "Add Class Modifier",
  "Replace Loop With Pipeline",
  "Add Method Modifier",
  "Extract And Move Method",
  "Add Class Annotation",
  "Change Type Declaration Kind",
  "Parameterize Variable",
  "Encapsulate Attribute",
  "Replace Attribute With Variable",
  "Move And Inline Method",
  "Modify Parameter Annotation",
  "Remove Method Annotation",
  "Modify Method Annotation",
  "Remove Variable Modifier",
  "Move Class",
  "Replace Anonymous With Lambda",
  "Change Class Access Modifier",
  "Extract Interface",
  "Add Parameter Modifier",
  "Extract Attribute",
  "Rename Class",
  "Replace Variable With Attribute",
  "Modify Class Annotation",
  "Replace Variable With Attribute",
  "Extract Variable",
  "Add Method Annotation",
  "Remove Method Annotation",
  "Remove Thrown Exception Type",
  "Inline Method",
  "Extract Method",
  "Rename Variable",
  "Change Attribute Type",
  "Inline Variable",
  "Add Parameter",
  "Move Method",
  "Change Variable Type",
  "Change Method Access Modifier",
  "Add Thrown Exception Type",
  "Parameterize Variable",
  "Remove Parameter",
  "Add Method Modifier",
  "Rename Parameter",
  "Rename Method",
  "Extract And Move Method",
  "Change Parameter Type",
  "Change Return Type",
  "Move And Inline Method",
  "Remove Variable Annotation",
  "Remove Method Modifier",
  "Encapsulate Attribute",
  "Remove Attribute Modifier",
  "Rename Class",
  "Rename Attribute",
  "Move Class",
  "Change Class Access Modifier",
  "Add Class Modifier",
  "Move Attribute",
  "Move And Rename Method",
  "Add Attribute Modifier",
  "Remove Variable Modifier",
  "Change Attribute Access Modifier",
  "Remove Class Modifier",
  "Reorder Parameter",
  "Change Thrown Exception Type",
  "Extract Attribute",
  "Pull Up Attribute",
  "Remove Thrown Exception Type",
  "Add Method Annotation",
  "Extract Method",
  "Change Variable Type",
  "Add Class Modifier",
  "Inline Method",
  "Change Method Access Modifier",
  "Change Attribute Type",
  "Change Parameter Type",
  "Rename Method",
  "Rename Variable",
  "Rename Parameter",
  "Add Attribute Modifier",
  "Inline Variable",
  "Localize Parameter",
  "Change Return Type",
  "Add Parameter",
  "Remove Method Modifier",
  "Remove Variable Modifier",
  "Extract Class",
  "Move Attribute",
  "Change Attribute Access Modifier",
  "Remove Parameter",
  "Rename Attribute",
  "Add Thrown Exception Type",
  "Extract Variable",
  "Push Down Attribute",
  "Parameterize Variable",
  "Remove Method Annotation",
  "Add Method Modifier",
  "Remove Attribute Modifier",
  "Add Attribute Annotation",
  "Move Class",
  "Replace Variable With Attribute",
  "Replace Attribute With Variable",
  "Change Class Access Modifier",
  "Move And Rename Method",
  "Move Method",
  "Extract And Move Method",
  "Move And Inline Method",
  "Extract Attribute",
  "Encapsulate Attribute",
  "Remove Attribute Annotation",
  "Replace Pipeline With Loop",
  "Add Variable Modifier",
  "Remove Class Modifier",
  "Replace Anonymous With Lambda",
  "Move And Rename Attribute",
  "Remove Class Annotation",
  "Extract Subclass",
  "Push Down Method",
  "Modify Method Annotation",
  "Rename Class",
  "Merge Parameter",
  "Merge Variable",
  "Extract Interface",
  "Modify Attribute Annotation",
  "Split Parameter",
  "Parameterize Attribute",
  "Move And Rename Class",
  "Merge Class",
  "Add Parameter Modifier",
  "Remove Parameter Modifier",
  "Add Class Annotation",
];

const newData = new Set(rr);
console.log(newData);

// Refactoring types detected in studied projects.
"Extract Variable",
  "Change Variable Type",
  "Rename Variable",
  "Change Attribute Type",
  "Remove Attribute Modifier",
  "Extract Superclass",
  "Move Attribute",
  "Change Attribute Access Modifier",
  "Add Attribute Modifier",
  "Pull Up Attribute",
  "Pull Up Method",
  "Remove Thrown Exception Type",
  "Move Method",
  "Change Return Type",
  "Rename Parameter",
  "Change Parameter Type",
  "Localize Parameter",
  "Add Parameter",
  "Rename Method",
  "Rename Attribute",
  "Modify Attribute Annotation",
  "Remove Parameter",
  "Add Method Annotation",
  "Change Method Access Modifier",
  "Inline Method",
  "Extract Method",
  "Remove Class Modifier",
  "Remove Parameter Modifier",
  "Add Variable Modifier",
  "Inline Variable",
  "Remove Method Modifier",
  "Add Class Modifier",
  "Replace Loop With Pipeline",
  "Add Method Modifier",
  "Extract And Move Method",
  "Add Class Annotation",
  "Change Type Declaration Kind",
  "Parameterize Variable",
  "Encapsulate Attribute",
  "Replace Attribute With Variable",
  "Move And Inline Method",
  "Modify Parameter Annotation",
  "Remove Method Annotation",
  "Modify Method Annotation",
  "Remove Variable Modifier",
  "Move Class",
  "Replace Anonymous With Lambda",
  "Change Class Access Modifier",
  "Extract Interface",
  "Add Parameter Modifier",
  "Extract Attribute",
  "Rename Class",
  "Replace Variable With Attribute",
  "Modify Class Annotation",
  "Add Thrown Exception Type",
  "Remove Variable Annotation",
  "Move And Rename Method",
  "Reorder Parameter",
  "Change Thrown Exception Type",
  "Extract Class",
  "Push Down Attribute",
  "Add Attribute Annotation",
  "Remove Attribute Annotation",
  "Replace Pipeline With Loop",
  "Move And Rename Attribute",
  "Remove Class Annotation",
  "Extract Subclass",
  "Push Down Method",
  "Merge Parameter",
  "Merge Variable",
  "Split Parameter",
  "Parameterize Attribute",
  "Move And Rename Class",
  "Merge Class";
